export default function Terms() {
  return (
    <main style={styles.main}>
      <h1 style={styles.h1}>Admit<span style={{ color: '#E8735A' }}>ly</span> — Terms of Service</h1>
      <p style={styles.updated}>Last updated: [add today's date when you publish this]</p>

      <h2 style={styles.h2}>What Admitly is</h2>
      <p style={styles.p}>
        Admitly gives AI-generated feedback on essays you write yourself — it points out clichés,
        vague lines, and weak openings, and suggests specific rewrites. It does not write essays
        for you, and it is not a guarantee of any admissions or scholarship outcome.
      </p>

      <h2 style={styles.h2}>Plans</h2>
      <ul style={styles.ul}>
        <li>Free plan: 2 essay reviews per month, 1 feedback round each.</li>
        <li>Unlimited plan: $12/month, unlimited essays and feedback rounds, cancel anytime.</li>
      </ul>

      <h2 style={styles.h2}>Billing</h2>
      <p style={styles.p}>
        Paid subscriptions are billed monthly through Stripe. You can cancel at any time; your
        access continues through the end of the billing period you already paid for. We don't
        offer refunds for partial months, but canceling stops all future charges immediately.
      </p>

      <h2 style={styles.h2}>Using Admitly fairly</h2>
      <p style={styles.p}>
        Please don't create multiple accounts to get around the free-plan limit, and please only
        submit writing that's actually your own — Admitly is a feedback tool to help you improve
        your own essay, not a way to have an essay written for you.
      </p>

      <h2 style={styles.h2}>No guarantee</h2>
      <p style={styles.p}>
        Feedback is generated by an AI model and reflects one perspective, not a certified
        admissions officer's judgment. Use your own judgment alongside it — it's a tool to help
        you revise, not a promise of any particular result.
      </p>

      <h2 style={styles.h2}>Service "as is"</h2>
      <p style={styles.p}>
        Admitly is provided as-is, without warranties of any kind. We're not liable for any
        outcome related to your application, essay, or admissions decision.
      </p>

      <h2 style={styles.h2}>Governing law</h2>
      <p style={styles.p}>These terms are governed by the laws of the State of Rhode Island.</p>

      <h2 style={styles.h2}>Contact</h2>
      <p style={styles.p}>
        Questions about these terms? Email <a href="mailto:hello@admitly.io">hello@admitly.io</a>.
      </p>
    </main>
  );
}

const styles: Record<string, React.CSSProperties> = {
  main: { maxWidth: 680, margin: '0 auto', padding: '48px 24px', fontFamily: 'Inter, sans-serif', color: '#2E2A24', lineHeight: 1.6 },
  h1: { fontFamily: 'Fraunces, serif', fontSize: 32, marginBottom: 4 },
  h2: { fontFamily: 'Fraunces, serif', fontSize: 20, marginTop: 32, marginBottom: 10 },
  p: { fontSize: 15, color: '#6F6A5D', marginBottom: 12 },
  ul: { fontSize: 15, color: '#6F6A5D', paddingLeft: 20, marginBottom: 12 },
  updated: { fontSize: 13, color: '#948C7C', marginBottom: 24 },
};
